# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - go test -run ""
  build:
    cmds:
      - go build -o circus main.go
  lint:
    cmds:
      - golangci-lint run
  run:
    cmds:
      - ./circus server --config settings.yaml